# Generated by Django 5.1.4 on 2024-12-10 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('trade_id', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('volume', models.FloatField()),
                ('price_open', models.FloatField()),
                ('price_close', models.FloatField()),
                ('profit', models.FloatField()),
                ('create_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaTraderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.TextField(null=True)),
                ('key_code', models.TextField(null=True)),
                ('server', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
