# Generated by Django 5.1.4 on 2024-12-13 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTraderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255, null=True)),
                ('account_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.TextField(null=True)),
                ('key_code', models.BinaryField(null=True)),
                ('server', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cached_at', models.DateTimeField(null=True)),
                ('cached_until', models.DateTimeField(null=True)),
                ('balance', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255, null=True)),
                ('volume', models.FloatField(blank=True, default=0, null=True)),
                ('duration_in_minutes', models.FloatField(blank=True, default=0, null=True)),
                ('profit', models.FloatField(blank=True, default=0, null=True)),
                ('gain', models.FloatField(blank=True, default=0, null=True)),
                ('success', models.CharField(blank=True, max_length=255, null=True)),
                ('open_time', models.DateTimeField(blank=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
