# Generated by Django 5.1.4 on 2024-12-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='symbol',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
