# Generated by Django 5.1.4 on 2024-12-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrade', '0002_trade_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
