# Generated by Django 5.1.4 on 2024-12-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrade', '0003_metatraderaccount_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatraderaccount',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
