# Generated by Django 5.1.4 on 2024-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrade', '0003_metatraderaccount_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatraderaccount',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='metatraderaccount',
            name='key_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='metatraderaccount',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='metatraderaccount',
            name='server',
            field=models.CharField(max_length=255),
        ),
    ]
