# Generated by Django 5.1.4 on 2024-12-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrade', '0003_trade_trade_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
