# Generated by Django 5.1.4 on 2024-12-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metatrade', '0004_alter_metatraderaccount_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metatraderaccount',
            name='api_token',
        ),
    ]
