# Generated by Django 5.1.4 on 2025-01-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrade', '0004_trade_close_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='is_top_up',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
