# Generated by Django 5.1.4 on 2024-12-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrade', '0005_remove_trade_user_id_trade_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='trade_id',
            new_name='account_id',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='price_close',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='price_open',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='symbol',
        ),
        migrations.AddField(
            model_name='trade',
            name='duration_in_minutes',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='gain',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='open_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='success',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='volume',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
