# Generated by Django 5.1.4 on 2024-12-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrade', '0005_remove_metatraderaccount_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatraderaccount',
            name='account_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metatraderaccount',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='metatraderaccount',
            name='cached_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='metatraderaccount',
            name='cached_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='account_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
