# Generated by Django 5.1.4 on 2024-12-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrade', '0006_rename_trade_id_trade_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatraderaccount',
            name='account_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
