# Generated by Django 5.1.4 on 2024-12-13 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrade', '0006_metatraderaccount_account_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='price_close',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='price_open',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='trade_id',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='user_id',
        ),
        migrations.AddField(
            model_name='trade',
            name='duration_in_minutes',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='gain',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='open_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='success',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='volume',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
