# Generated by Django 5.1.4 on 2024-12-09 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tradeaccount_manualtrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateField(blank=True, null=True)),
                ('trade_note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_notes', to='users.manualtrade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
