# Generated by Django 5.1.4 on 2024-12-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_date_of_birth"),
        ("users", "0003_tradenote"),
    ]

    operations = []
