# Generated by Django 5.1.4 on 2024-12-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_manualtrade_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualtrade',
            name='account',
        ),
    ]
