# Generated by Django 5.1.4 on 2024-12-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_manualtrade_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manualtrade",
            name="notes",
        ),
        migrations.AlterField(
            model_name="manualtrade",
            name="quantity",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
