# Generated by Django 5.1.4 on 2024-12-14 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_manualtrade_price_alter_manualtrade_symbol_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manualtrade",
            name="user",
        ),
        migrations.AddField(
            model_name="manualtrade",
            name="account",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_trades",
                to="users.tradeaccount",
            ),
            preserve_default=False,
        ),
    ]
