# Generated by Django 5.1.4 on 2025-01-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_uploadedfile_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manualtrade",
            old_name="close_date",
            new_name="close_time",
        ),
        migrations.RenameField(
            model_name="manualtrade",
            old_name="trade_date",
            new_name="open_time",
        ),
        migrations.RemoveField(
            model_name="manualtrade",
            name="price",
        ),
        migrations.RemoveField(
            model_name="manualtrade",
            name="total_amount",
        ),
        migrations.RemoveField(
            model_name="tradeaccount",
            name="name",
        ),
        migrations.AddField(
            model_name="manualtrade",
            name="close_price",
            field=models.DecimalField(decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name="manualtrade",
            name="exchange_id",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="manualtrade",
            name="is_top_up",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="manualtrade",
            name="open_price",
            field=models.DecimalField(decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name="tradeaccount",
            name="account_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tradeaccount",
            name="account_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tradeaccount",
            name="cached_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="tradeaccount",
            name="cached_until",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="tradeaccount",
            name="currency",
            field=models.CharField(default="USD", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="tradeaccount",
            name="platform",
            field=models.CharField(
                choices=[
                    ("MetaTrader4", "Meta Trader 4"),
                    ("MetaTrader5", "Meta Trader 5"),
                    ("TradeLocker", "Trade Locker"),
                    ("CTrader", "C Trader"),
                    ("Manual", "Manual"),
                ],
                default="Manual",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="tradeaccount",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="manualtrade",
            name="trade_type",
            field=models.CharField(
                blank=True,
                choices=[("Buy", "Buy"), ("Sell", "Sell")],
                max_length=4,
                null=True,
            ),
        ),
    ]
