# Generated by Django 5.1.4 on 2025-01-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeaccount',
            name='credentials',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
