# Generated by Django 5.1.4 on 2025-01-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_tradeaccount_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
