# Generated by Django 5.1.4 on 2025-01-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtrade',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
