# Generated by Django 5.1.4 on 2025-01-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_manualtrade_active_tradeaccount_disabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualtrade",
            name="quantity",
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
