# Generated by Django 5.1.4 on 2025-01-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_manualtrade_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualtrade',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
