# Generated by Django 5.1.4 on 2025-02-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_exchangerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeaccount',
            name='status',
        ),
        migrations.AddField(
            model_name='tradeaccount',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tradeaccount',
            name='server',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
