# Generated by Django 4.2.7 on 2025-02-05 07:26

from django.db import migrations, models
import users.storage_backend


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_uploadedfile_trade_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.ImageField(blank=True, null=True, storage=users.storage_backend.MediaStorage(), upload_to='tradesImagesUpload/'),
        ),
    ]
