# Generated by Django 5.1.4 on 2024-12-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradableInstrumentId', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('tradingExchange', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('logoUrl', models.CharField(max_length=255)),
                ('localizedName', models.CharField(max_length=255)),
                ('routes', models.TextField()),
                ('barSource', models.CharField(max_length=255)),
                ('hasIntraday', models.BooleanField()),
                ('hasDaily', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.CharField(max_length=255)),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('trade_id', models.CharField(max_length=255, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('volume', models.FloatField()),
                ('price_open', models.FloatField()),
                ('price_close', models.FloatField()),
                ('profit', models.FloatField()),
                ('create_time', models.DateTimeField()),
                ('close_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
