# Generated by Django 5.1.4 on 2024-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_locker', '0003_traderlockeraccount_delete_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderlockeraccount',
            name='demo_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='traderlockeraccount',
            name='key_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='traderlockeraccount',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='traderlockeraccount',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
