# Generated by Django 5.1.4 on 2024-12-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_locker', '0003_traderlockeraccount_delete_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderlockeraccount',
            name='demo_status',
            field=models.BooleanField(default=True),
        ),
    ]
