# Generated by Django 5.1.4 on 2024-12-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_locker', '0004_traderlockeraccount_demo_status'),
        ('trade_locker', '0004_traderlockeraccount_demo_status_and_more'),
    ]

    operations = [
    ]
