# Generated by Django 5.1.4 on 2024-12-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_locker', '0005_merge_20241210_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderlockeraccount',
            name='key_code',
            field=models.BinaryField(null=True),
        ),
    ]
