# Generated by Django 5.1.4 on 2024-12-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_locker', '0008_rename_trader_orderhistory_trader_locker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='instrument_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
