# Generated by Django 5.1.4 on 2024-12-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_locker', '0007_traderlockeraccount_account_name'),
        ('trade_locker', '0009_alter_orderhistory_amount_and_more'),
    ]

    operations = [
    ]
