# Generated by Django 5.1.4 on 2024-12-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_locker', '0010_merge_20241211_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderlockeraccount',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
