# Generated by Django 5.1.4 on 2024-12-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ctraderaccount",
            name="account_name",
            field=models.CharField(null=True),
        ),
    ]
