# Generated by Django 5.1.4 on 2024-12-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrader", "0003_alter_ctraderaccount_account_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ctraderaccount",
            name="account_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
